### PR TITLE
add a katex directory for extensions

### PR DESCRIPTION
**Pull request by bashbaug**
This is the "path of least resistance" fix for the missing katex files described in https://github.com/KhronosGroup/OpenCL-Docs/issues/677.

It adds a local copy of the katex files in the extensions directory while we're figuring out if a more centralized location can be used instead.

### CODE REVIEW

**Comment by oddhack** [comment]
@outofcontrol could use some mod_rewrite advice here. I tried adding this rule to the end of registry/.htaccess:

> RewiteRule ^OpenCL/extensions/katex/?(.*)$ https://www.khronos.org/registry/OpenCL/specs/3.0-unified/katex/$1 [L,NC,R=301]

and the result seemed to be that any URL under registry/ was 404ed. Are there server logs I can look at to see what's happening? This seemed really obvious since it was just the same sort of pattern as dozens of others in .htaccess and I'm confused (rule is currently commented out).

**Comment by outofcontrol** [comment]
Adding a missing `r` to `RewriteRule` seems to allow the rule to work as expected.

**Comment by oddhack** [comment]
@bashbaug please check to make certain, but with @outofcontrol's fix, I believe there's no need for a second copy of katex - references to ...extensions/katex/ should be rewritten to the 3.0-unified version. If that is working for you, then this PR could be closed.

**Comment by bashbaug** [comment]
> If that is working for you, then this PR could be closed.

I think @outofcontrol filed the original issue this is aimed to fix: https://github.com/KhronosGroup/OpenCL-Docs/issues/677.

I can check this myself but I'm not sure how.

**Pull request closed without merging**
