### PR TITLE
publish ext image extensions

### PR DESCRIPTION
**Pull request by bashbaug**
* cl_ext_image_from_buffer (spec source PR: https://github.com/KhronosGroup/OpenCL-Docs/pull/752)
* cl_ext_image_requirements_info (spec source PR: https://github.com/KhronosGroup/OpenCL-Docs/pull/750)

### CODE REVIEW

**Comment by kpet** [comment]
@bashbaug I've created https://github.com/KhronosGroup/OpenCL-Docs/pull/942 to tidy up the sources. I see what you mean regarding the indentation but I've exhausted the time I could afford to spend convincing asciidoctor to not do that. I don't think it's ugly enough to require blocking publication but if you happen to know the magic runes to align those paragraphs, any pointers would be welcome! :)

**Comment by bashbaug** [comment]
I've rebuilt the specs after merging https://github.com/KhronosGroup/OpenCL-Docs/pull/942.  I think this is ready to go now.

For the record, I think it's a little weird to publish a shipping spec as v0.5, but if this is intended I don't think it should block publication.

Thanks!

**Comment by bashbaug** [comment]
Here are some links to help review:

* https://htmlpreview.github.io/?https://github.com/bashbaug/OpenCL-Registry/blob/publish-ext-image-extensions/extensions/ext/cl_ext_image_from_buffer.html
* https://htmlpreview.github.io/?https://github.com/bashbaug/OpenCL-Registry/blob/publish-ext-image-extensions/extensions/ext/cl_ext_image_requirements_info.html

**Review by kpet — APPROVED** [review]
Thanks, all looking good!

**Pull request merged**
