### PR TITLE
signpost KHR text extensions to the OpenCL Extension Spec

### PR DESCRIPTION
**Pull request by bashbaug**
This pull request modifies the plaintext KHR extension specs for `cl_khr_icd`, `cl_khr_d3d10_sharing`, and `cl_khr_gl_sharing`.

All KHR extensions are currently described in the OpenCL extensions spec.  These three extensions are unique, since they also have individual, plaintext extension specs on the registry.

Rather than keeping the individual, plaintext extension specs in sync with the definitions in the OpenCL extensions spec, this pull request replaces the plaintext extension specs with signposts to the OpenCL extensions spec (and the corresponding asciidoc sources), which are now the normative specifications for these extensions.

### CODE REVIEW

**Comment by bashbaug** [comment]
Ping @oddhack, any concerns with this PR?

**Comment by oddhack** [comment]
Looks fine.

**Comment by oddhack** [comment]
I could tweak the registry index to redirect links for these extensions to the asciidoctor spec, though I'm not sure it's worth the trouble.

**Comment by bashbaug** [comment]
> though I'm not sure it's worth the trouble.

I agree, it's not worth the trouble, and I think the signposts provide more information than a link to the asciidoc spec source anyhow.

If there are no remaining issues or concerns can this PR be merged?

**Pull request merged**
