### PR TITLE
Rename cl_intel_thread_local_exec to cl_intel_exec_by_local_thread

### PR DESCRIPTION
**Pull request by fzou1**
cl_intel_exec_by_local_thread is the correct extension name.

### CODE REVIEW

**Review by bashbaug — CHANGES_REQUESTED** [review]
Thanks for fixing this!

I think a few additional changes are required as well due to the filename change:

* Can you please change the name of the extension and the path to the file in `registry.py`?
* After doing this, can you please run make to regenerate `clext.php`?

This way the link to the specification will not be broken on the registry.  Thanks!

**Comment by fzou1** [comment]
@bashbaug , Thank you for the reminder. Updated.

**Review by bashbaug — APPROVED** [review]
Thanks!

**Comment by bashbaug** [comment]
It looks like there are a couple of other places that have the old name of the extension too (not in this repo):

In the headers:
https://github.com/KhronosGroup/OpenCL-Headers/blob/master/CL/cl_ext.h#L1301

In the XML file:
https://github.com/KhronosGroup/OpenCL-Docs/blob/master/xml/cl.xml#L5563

It'd be great to get these fixed too - thanks!

**Comment by fzou1** [comment]
> It looks like there are a couple of other places that have the old name of the extension too (not in this repo):
> 
> In the headers: https://github.com/KhronosGroup/OpenCL-Headers/blob/master/CL/cl_ext.h#L1301
> 
> In the XML file: https://github.com/KhronosGroup/OpenCL-Docs/blob/master/xml/cl.xml#L5563
> 
> It'd be great to get these fixed too - thanks!

Created PRs:
https://github.com/KhronosGroup/OpenCL-Headers/pull/183
https://github.com/KhronosGroup/OpenCL-Docs/pull/716

**Pull request merged**
