### PR TITLE
update the OpenCL reference pages for v3.0.10

### PR DESCRIPTION
**Pull request by bashbaug**
Updates the online OpenCL reference pages for the v3.0.10 specs.

### CODE REVIEW

**Comment by oddhack** [comment]
Maybe we should consider not inlining the CSS for the refpages? Mostly to make the PR diff listing more comprehensible, more than for space savings.

**Comment by bashbaug** [comment]
Yeah, I noticed that.  We updated the stylesheets and there are a lot more diffs this time than there were previously.

Is this an easy change to the reference page toolchain?

**Review by alycm — APPROVED** [review]
LGTM, in so far as I checked.  I made sure a couple of changes that should be there were there.

As stated above, the amount of CSS changes makes it hard to do a "full" review.

Presumably moving the CSS is not a blocker for merging though?

**Comment by oddhack** [comment]
> Yeah, I noticed that. We updated the stylesheets and there are a lot more diffs this time than there were previously.
> 
> Is this an easy change to the reference page toolchain?

Yes. I can prototype it if you like (please open a tracking issue against me if so), or you can look at https://docs.asciidoctor.org/asciidoctor/latest/html-backend/stylesheet-modes/#embed . TL;DR will need to set the linkcss and copycss attributes appropriately. We don't do this by default since there's some value in keeping the files entirely self-contained and some slight complexity in getting the right stylesheet bundled with the refpages - but the process looks to have gotten a bit simpler since we made that decision years ago in Vulkan.

**Comment by bashbaug** [comment]
Closing - we should merge the v3.0.11 reference pages instead (https://github.com/KhronosGroup/OpenCL-Registry/pull/122).

**Pull request closed without merging**
