### PR TITLE
error codes for upcoming Intel extension

### PR DESCRIPTION
**Pull request by bashbaug**
Please reserve eight error codes for an upcoming Intel extension.

### CODE REVIEW

**Comment by VincentSC** [comment]
Is there an overview of these errors? From what I've collected at https://streamcomputing.eu/blog/2013-04-28/opencl-error-codes/ it seems I'm probably missing errors -1014 to -1101, or at least -1100 and -1101.

**Comment by VincentSC** [comment]
Managed to find -1092 to -1101.
The error range -1014 to -1091 is reserved for what specifically?

**Comment by bashbaug** [comment]
I believe that all of the Intel error codes are correctly documented in the registry, except for -1102 to -1109 (inclusive).  The error range -1014 to -1091 is allocated to several other vendors.  

The error code range -1102 to -1109 allocated to Intel is planned for use by several extensions that Intel has not published yet, even as "preview extensions".

**Comment by oddhack** [comment]
@VincentSC as a general matter, reservations don't have a publicly known purpose until the vendor who reserved them publishes a corresponding extension spec. There will always be reserved ranges for purposes which aren't known to anyone except the vendor, and sometimes they reserve blocks speculatively (NVIDIA does this a lot with OpenGL, for example) to give themselves room for growth.

**Comment by VincentSC** [comment]
Ok, thanks for the clarification.
While searching for documented errors in the range 10xx, I found duplicates of 4 errors:
- https://www.khronos.org/registry/OpenCL/extensions/intel/cl_intel_dx9_media_sharing.txt
- https://www.khronos.org/registry/OpenCL/extensions/nv/cl_nv_d3d9_sharing.txt
Is this done on purpose?

**Comment by oddhack** [comment]
Likely so. I believe they were both developing D3D9 interop functionality at the same time and there were some common discussions, although that was a very long time ago.

**Comment by VincentSC** [comment]
Thanks. Sorry for taking over the conversation.

**Pull request merged**
